#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');
const pkg = require('../package.json');

const helpMessage = childProcess
  .execSync(
    './bin/muxify --help',
    { encoding: 'utf-8'},
  )
  .toString();

const helpMessageReplacedREADME = fs
  .readFileSync(
    path.resolve(__dirname, './readme-template.md'),
    { encoding: 'utf-8' }
  )
  .toString()
  .replace('%HELP_MESSAGE%', helpMessage)
  .replace('%DESCRIPTION_PLACEHOLDER%', pkg.description);

fs.writeFileSync(
  path.join(__dirname, '../README.md'),
  helpMessageReplacedREADME,
  { encoding: 'utf-8' }
);

const unreleasedReplacedCHANGELOG = fs
  .readFileSync(
    path.resolve(__dirname, '../CHANGELOG.md'),
    { encoding: 'utf-8' }
  )
  .toString()
  .replace('## Unreleased', `## ${process.env.npm_new_version}`);

fs.writeFileSync(
  path.join(__dirname, '../CHANGELOG.md'),
  unreleasedReplacedCHANGELOG,
  { encoding: 'utf-8' }
);
