name: Prepublish GPR

on:
  workflow_run:
    workflows:
      - Prerelease
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Set Git Default Branch
        run: |
          git config --global init.defaultBranch main
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          registry-url: 'https://npm.pkg.github.com'
      - name: Upgrade NPM
        run: npm install --global npm
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build Package
        run: pnpm run build
      - name: Publish to GPR
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
